services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: angular-app-container
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

  # Opcional: Agregar una base de datos si es necesario
  # postgres:
  #   image: postgres:13-alpine
  #   container_name: postgres-db
  #   environment:
  #     POSTGRES_DB: myapp
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

# volumes:
#   postgres_data: